# Generated by Django 6.0.7 on 2026-07-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0002_alter_location_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='landmark',
            new_name='formatted_address',
        ),
        migrations.RemoveField(
            model_name='location',
            name='pin_location',
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
