# Generated by Django 6.0.7 on 2026-07-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.IntegerField(unique=True)),
                ('daily_earning', models.PositiveIntegerField(default=0)),
                ('weekly_earning', models.PositiveIntegerField(default=0)),
                ('total_earning', models.PositiveIntegerField(default=0)),
                ('jobs_done', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
