# Generated by Django 6.0.7 on 2026-07-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Earning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workerearnings',
            old_name='jobs_done',
            new_name='daily_jobs_done',
        ),
        migrations.AddField(
            model_name='workerearnings',
            name='total_jobs_done',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
