# Generated by Django 6.0.7 on 2026-07-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('attachment_id', models.IntegerField(blank=True, null=True)),
                ('price', models.PositiveIntegerField()),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by_id', models.IntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('preffered_time', models.CharField()),
                ('location_id', models.IntegerField()),
                ('status_id', models.IntegerField()),
                ('payment_preference_id', models.IntegerField()),
                ('accurately_estimated', models.IntegerField()),
                ('catergory_id', models.IntegerField()),
            ],
        ),
    ]
