# Generated by Django 6.0.7 on 2026-07-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='catergory_id',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='preffered_time',
            new_name='preferred_time',
        ),
    ]
