# Generated by Django 6.0.7 on 2026-07-10 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_rename_catergory_id_task_category_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='attachment_id',
        ),
    ]
