# Generated by Django 6.0.7 on 2026-07-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_remove_task_attachment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='worker_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
