# Generated by Django 6.0.7 on 2026-07-27 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0004_task_worker_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='category_id',
            new_name='subcategory_id',
        ),
    ]
