# Generated by Django 6.0.7 on 2026-07-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attachment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='task_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
