# Generated by Django 6.0.6 on 2026-07-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_user_overall_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
