# Generated by Django 6.0.6 on 2026-07-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_remove_location_area_remove_location_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location_zip_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
