# Generated by Django 6.0.7 on 2026-07-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_alter_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_earning',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='jobs_done',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='total_earning',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='weekly_earning',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
