# Generated by Django 6.0.7 on 2026-07-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_user_daily_earning_user_jobs_done_user_total_earning_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='daily_earning',
        ),
        migrations.RemoveField(
            model_name='user',
            name='jobs_done',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_earning',
        ),
        migrations.RemoveField(
            model_name='user',
            name='weekly_earning',
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
