# Generated by Django 6.0.7 on 2026-07-28 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('sender_id', models.IntegerField()),
                ('body', models.TextField()),
                ('sequence', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='Message.message')),
            ],
            options={
                'ordering': ['sequence'],
                'indexes': [models.Index(fields=['room_id', 'sequence'], name='Message_mes_room_id_9a2842_idx')],
            },
        ),
    ]
