# Generated by Django 6.0.7 on 2026-07-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
