# Generated by Django 6.0.7 on 2026-07-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verify_attachment_id_back',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='verify_attachment_id_front',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
