# Generated by Django 6.0.7 on 2026-07-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachments', models.SmallIntegerField()),
                ('row_items', models.SmallIntegerField()),
            ],
        ),
    ]
